# Generated by Django 3.2 on 2021-05-26 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaoNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bao_number', models.IntegerField(unique=True, verbose_name='包号')),
                ('start_work_time', models.DateTimeField(verbose_name='开始服役时间')),
                ('on_line', models.BooleanField(verbose_name='在线状态')),
                ('bao_empty', models.CharField(default='', max_length=200, verbose_name='空信息')),
            ],
        ),
        migrations.CreateModel(
            name='PublicInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_time', models.DateTimeField(verbose_name='时间戳')),
                ('first_temp_area', models.CharField(max_length=50, verbose_name='高温区域1')),
                ('first_temp_value', models.CharField(max_length=50, verbose_name='高温值1')),
                ('second_temp_area', models.CharField(max_length=50, verbose_name='高温区域2')),
                ('second_temp_value', models.CharField(max_length=50, verbose_name='高温值2')),
                ('first_empty', models.CharField(default='', max_length=200, verbose_name='空信息1')),
                ('second_empty', models.CharField(default='', max_length=200, verbose_name='空信息2')),
                ('third_empty', models.CharField(default='', max_length=200, verbose_name='空信息3')),
                ('bao_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baoinformation.baonumber')),
            ],
            options={
                'verbose_name': '包况信息',
                'verbose_name_plural': '包况信息',
                'ordering': ['-b_time'],
            },
        ),
    ]
