# Generated by Django 3.2 on 2021-05-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baoinformation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hardware', models.CharField(max_length=50, unique=True, verbose_name='硬件名称')),
                ('operation_status', models.BooleanField(verbose_name='运行状态')),
                ('hardware_online_time', models.DateTimeField(verbose_name='硬件上线时间')),
                ('factory', models.CharField(max_length=50, verbose_name='硬件厂商')),
            ],
        ),
        migrations.CreateModel(
            name='MaintainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_event', models.CharField(max_length=200, verbose_name='维护事件')),
                ('m_event_time', models.DateTimeField(auto_now_add=True, verbose_name='维护事件添加时间')),
            ],
            options={
                'verbose_name': '维护事件',
                'verbose_name_plural': '维护事件',
                'ordering': ['-m_event_time'],
            },
        ),
        migrations.AlterField(
            model_name='baonumber',
            name='bao_empty',
            field=models.CharField(default='1', max_length=200, verbose_name='空信息'),
        ),
        migrations.AlterField(
            model_name='publicinformation',
            name='b_time',
            field=models.DateTimeField(verbose_name='包况时间戳'),
        ),
        migrations.AlterField(
            model_name='publicinformation',
            name='first_empty',
            field=models.CharField(default='1', max_length=200, verbose_name='空信息1'),
        ),
        migrations.AlterField(
            model_name='publicinformation',
            name='second_empty',
            field=models.CharField(default='1', max_length=200, verbose_name='空信息2'),
        ),
        migrations.AlterField(
            model_name='publicinformation',
            name='third_empty',
            field=models.CharField(default='1', max_length=200, verbose_name='空信息3'),
        ),
        migrations.CreateModel(
            name='MaintainInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_time', models.DateTimeField(verbose_name='维护时间')),
                ('m_information', models.CharField(max_length=200, verbose_name='维护信息')),
                ('m_description', models.CharField(max_length=200, verbose_name='维护说明')),
                ('m_empty', models.CharField(default='1', max_length=200, verbose_name='空信息')),
                ('bao_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baoinformation.baonumber')),
            ],
            options={
                'verbose_name': '维护信息',
                'verbose_name_plural': '维护信息',
                'ordering': ['-m_time'],
            },
        ),
    ]
