# Generated by Django 3.2 on 2021-05-26 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baoinformation', '0002_auto_20210526_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baonumber',
            options={'verbose_name': '包号信息', 'verbose_name_plural': '包号信息'},
        ),
        migrations.AlterModelOptions(
            name='hardware',
            options={'verbose_name': '硬件信息', 'verbose_name_plural': '硬件信息'},
        ),
        migrations.AddField(
            model_name='publicinformation',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='删除'),
        ),
    ]
